version: "3"
services:
  db:
    image: postgres:alpine
    pull_policy: always
    restart: unless-stopped
    ports:
      - 5433:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env.local

volumes:
  postgres:
