version: "3"
services:
  app:
    build: .
    pull_policy: always
    restart: unless-stopped
    ports:
      - ${APP_PORT}:3000
      - ${STUDIO_PORT}:5555
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/postgres?schema=public
    env_file:
      - .env.local
    depends_on:
      - db

  db:
    image: postgres:alpine
    pull_policy: always
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

volumes:
  postgres:
